name: Run tests

on: [push]

jobs:
    run-tests:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
            - name: Setup Golang with cache
              uses: magnetikonline/action-golang-cache@v4
              with:
                go-version: 1.19
            - run: go mod tidy
            - run: go test -v ./...
